### ISSUE TITLE
Lower case values in arrays

### ISSUE THREAD

**Issue by pcapazzi** [braze-inc/growth-shares-lambda-user-csv-import#11]
Hello,
We noticed that upper cased characters in arrays are loaded into Braze as lower case. This causes an issue when connecting that information to catalogs items. 

In the _process_value function the value is stripped and converted to lower case. It's tested to determine it's type. I think the lower case value is to test it again 'y', 'n' and 'null'.  After the test for 'false' it tests the structure of an array (value beginning with [ and ending with ]). The thing is that it's testing and returning the stripped _and lower cased_ version of the value. Is there a reason for this? 

One possible solution to preserve the case  would be to reset the stripped variable without the lower() function just before the last test:

```
stripped = value.strip()

    elif len(stripped) > 1 and stripped[0] == '[' and stripped[-1] == ']':
        try:
            return ast.literal_eval(stripped)
        except Exception:
            print("ERROR: Could not convert value to an array:", stripped)
            return stripped
```

**Comment by pcapazzi** [comment]
Submitted a change request.

**Comment by macolko** [comment]
@pcapazzi thank you!
