### ISSUE TITLE
AccessDeniedException when a 0 users file is processed

### ISSUE THREAD

**Issue by joel-iemma-moneybox** [braze-inc/growth-shares-lambda-user-csv-import#2]
We have a pipeline that produces multiple files with users and then sends them to the S3 bucket. Most of them are processed correctly but I receive an "AccessDeniedException" when the file has 0 users (only headers).

`An error occurred (AccessDeniedException) when calling the Invoke operation: User ... is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:eu-west-1:... because no identity-based policy allows the lambda:InvokeFunction action: ClientError`

Is this the expected outcome or should it be changed? In my opinion, 0 processed users should return success as there were no data points affected but I might be incorrect.

**Comment by macolko** [comment]
Hey @joel-iemma, thanks for letting us know about this issue.

I've already implemented the change, and it will be released in the Serverless Repository with the next update.
Meanwhile, you can patch your existing function by downloading the updated `zip` file from this [release](https://github.com/braze-inc/growth-shares-lambda-user-csv-import/releases/tag/v0.1.3.1).
To update the existing function, you just have to navigate to it in the AWS Console, click `Upload from`, then `.zip file`. Select the downloaded `.zip` file.

**Comment by joel-iemma-moneybox** [comment]
Thanks @macolko 
We've applied the changes yesterday but we are receiving these errors now:
`"Encountered errors processing some users: [{'type': 'no attributes provided', 'input_array': 'attributes', 'index': 2}..."`
`"Encountered error for user chunk. {"message":"Valid data must be provided in the 'attributes', 'events', or 'purchases' fields.",..."`

I believe this is due to the empty value attribute for a user, for example:
```
external_id,attribute1
"user123","abc"
"user456",
"user789","def"
```

This would log an error for "user456" but would still update the values for the other users (fortunately). Also, the "Processed N users" message seems to be affected by this.

The documentation mentions that empty valued attributes will be ignored. Any suggestion or should we wait for the next release?

**Comment by macolko** [comment]
Hi!

This is just a warning from Braze that no attributes were supplied and the user was not updated. It does not affect all other user updates but it will reduce the _Processed Users_ value because the values for the user were not updated.

If you want to get rid of this error, feel free to update your code with the [v0.1.3.2](https://github.com/braze-inc/growth-shares-lambda-user-csv-import/releases/tag/v0.1.3.2) release that will omit sending users with no updated attributes.

**Comment by macolko** [comment]
Release [v0.1.4](https://github.com/braze-inc/growth-shares-lambda-user-csv-import/releases/tag/v.0.1.4) consolidates these issues.
