### ISSUE TITLE
No users processed although there is valid data

### ISSUE THREAD

**Issue by joel-iemma-moneybox** [braze-inc/growth-shares-lambda-user-csv-import#4]
We have found times where we read "Processed 0 users" in the logs even though there is data qualified to be sent. This is a silent error given that it doesn't fail when these data points are not processed. We have already seen "Processed 0 users" many times but this was because all the values we empty. Therefore, the message in those cases is correct. Unfortunately, we have found over the last few days that it's also returning this message with files containing valid data. The same file uploaded with the CSV upload in the portal has worked ok. Code hasn't been changed since v0.1.4 

This silent error produces a mismatch between the data in braze and the actual user's data and affects the accuracy of the campaigns/targeting. 

![image](https://user-images.githubusercontent.com/82940249/145615522-d62ff758-bfb3-4b67-a4cc-a525a662d53f.png)
![image](https://user-images.githubusercontent.com/82940249/145615548-71676337-9a80-4d13-add9-f4ec8386b702.png)

Later the failed braze with 0 users file, was uploaded with the csv user import in the portal and worked ok.
![image](https://user-images.githubusercontent.com/82940249/145615565-b1126242-9cf8-41ac-b682-80715f497d97.png)

We have already filed a ticket with Braze Support, where we checked the data types of the fields but that was not clearly the issue. Then they have guided us here to open a new issue.

**Comment by macolko** [comment]
Hey @joel-iemma-moneybox,

Received the file from Braze Support. Looking into it 👍

**Comment by macolko** [comment]
Resolved with [0.1.5](https://github.com/braze-inc/growth-shares-lambda-user-csv-import/releases/tag/v0.1.5).

The application is also updated in the application repository.
