### ISSUE TITLE
restricted naming convention

### ISSUE THREAD

**Issue by sridhar-wal** [braze-inc/growth-shares-lambda-user-csv-import#9]
Hi I am trying to import users into braze from csv, for few users we are having **nan** as first name so at that time I am getting **Encountered error for user chunk** error. Can anyone help here how to handle that and also give me what are the restricted words? 

Please help me to return which users are not processed with their external id or email in the list format or any other format for the above issue because there is no index is displaying in the response at the same time for email validation i can able see the index in response.
  Thank you.

**Comment by macolko** [comment]
Hey, it's just a string `nan` value? 

You should be able to see which users were not imported successfully in the logs. https://github.com/braze-inc/growth-shares-lambda-user-csv-import#cloudwatch

**Comment by sridhar-wal** [comment]
Hi @macolko , Thanks for the reply but I am able to see only total number of processed users, there are no unprocessed users.

**Comment by macolko** [comment]
Whenever you get that message, the server rejected that request. Would you mind sharing a row of fake data that contains a cell with the `nan` value that causes the issue so I can try to replicate it?

**Comment by sridhar-wal** [comment]
`{
   "external_id":"user1",
   "email":"sample@gmail.com",
   "dob":"2000-01-01",
   "gender":"M",
   "first name": nan,
}`

I am passing `nan` as string but it is rejecting

**Comment by macolko** [comment]
Could you instead provide a CSV sample that's causing this issue?

**Comment by sridhar-wal** [comment]
[file1.csv](https://github.com/braze-inc/growth-shares-lambda-user-csv-import/files/10927751/file1.csv)
@macolko , please find attached csv

**Comment by sridhar-wal** [comment]
@macolko , Please find attached csv.
[file1.csv](https://github.com/braze-inc/growth-shares-lambda-user-csv-import/files/10927768/file1.csv)

**Comment by macolko** [comment]
Hey @sridhar-wal,
PR is up to fix it. 

You can also fix it by forcing the cast to string to the processor doesn't try to cast it to float by setting the ENV [`TYPE_CAST`](https://github.com/braze-inc/growth-shares-lambda-user-csv-import#forcing-a-data-type):
```
last_name=string
```
